"""add QuizScoreSubmission table

Revision ID: 0028e3cc4bdf
Revises: 180eb12409a9
Create Date: 2023-06-27 16:25:26.266142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0028e3cc4bdf'
down_revision = '180eb12409a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name=op.f('fk_quiz_scores_baby_id_babies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_scores')
    # ### end Alembic commands ###
