"""removed input and output tables

Revision ID: 181c7a32992e
Revises: 0028e3cc4bdf
Create Date: 2023-06-29 15:19:14.727643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181c7a32992e'
down_revision = '0028e3cc4bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inputs')
    op.drop_table('outputs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outputs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('baby_id', sa.INTEGER(), nullable=True),
    sa.Column('input_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name='fk_outputs_baby_id_babies'),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.id'], name='fk_outputs_input_id_inputs'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inputs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
