"""Added model_path to Baby

Revision ID: 4cc657e16087
Revises: 930534563919
Create Date: 2023-06-16 13:40:53.933359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc657e16087'
down_revision = '930534563919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('babies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('babies', schema=None) as batch_op:
        batch_op.drop_column('model_path')

    # ### end Alembic commands ###
